import { calcCash } from "./types";
import type { Product } from "./types";

export const products: Product[] = [
  // Хіти ціни
  { slug: "spiner-rk", name: "Спінер РК", nameRu: "Спинер РК", manufacturer: "PEST.UA", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Гліфосат (ізопропіламінна сіль)", activeIngredientRu: "Глифосат (изопропиламинная соль)",
    concentration: "480 г/л", packaging: "20 л", rate: "2,0–8,0 л/га",
    priceVat: 3.38, priceCash: calcCash(3.38), unit: "л", currency: "USD",
    analog: "Раундап", saveFromOriginal: 55,
    cultures: ["sonyashnyk", "kukurudza", "soya", "kartoplya"],
    stage: ["gruntovyi", "desikatsiya"],
    technology: ["klasyka", "clearfield", "express"],
    highlight: true,
    description: "Гербіцид суцільної дії для тотальної очистки полів до посіву та десикації перед збиранням.",
    descriptionRu: "Гербицид сплошного действия для тотальной очистки полей до посева и десикации перед уборкой.",
    image: "/products/spiner.jpg" },

  { slug: "gefest-pro", name: "Гефест Про", nameRu: "Гефест Про", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Гліфосат (калійна сіль)", activeIngredientRu: "Глифосат (калийная соль)",
    concentration: "614 г/л", packaging: "20 л", rate: "1,4–5,0 л/га",
    priceVat: 5.02, priceCash: calcCash(5.02), unit: "л", currency: "USD",
    analog: "Раундап Макс", saveFromOriginal: 33,
    cultures: ["sonyashnyk", "kukurudza", "soya"],
    stage: ["gruntovyi", "desikatsiya"],
    technology: ["klasyka", "clearfield", "express"],
    highlight: true,
    description: "Гліфосат калійної солі — швидше проникає в рослину, ефективніший в посуху.",
    descriptionRu: "Глифосат калийной соли — быстрее проникает в растение, эффективнее в засуху.",
    image: "/products/gefest-pro.jpg" },

  { slug: "satis", name: "Сатіс", nameRu: "Сатис", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Флорасулам + 2,4-Д ефір", activeIngredientRu: "Флорасулам + 2,4-Д эфир",
    concentration: "6,25 + 452 г/л", packaging: "5 л", rate: "0,4–0,6 л/га",
    priceVat: 5.17, priceCash: calcCash(5.17), unit: "л", currency: "USD",
    analog: "Прима (Corteva)", saveFromOriginal: 60,
    cultures: ["ozyma-pshenytsa", "yari-zernovi", "kukurudza", "sorgo"],
    stage: ["herbicid-vesna", "strakhovyi", "herbicid"],
    highlight: true,
    description: "Контроль дводольних бур'янів на зернових. Працює від +5°C — ідеально для ранньої весни.",
    descriptionRu: "Контроль двудольных сорняков на зерновых. Работает от +5°C — идеально для ранней весны.",
    image: "/products/satis.jpg" },

  { slug: "torlayting", name: "Торлайтінг", nameRu: "Торлайтинг", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Імазамокс + Імазапір", activeIngredientRu: "Имазамокс + Имазапир",
    concentration: "33 + 15 г/л", packaging: "20 л", rate: "1,0–1,2 л/га",
    priceVat: 9.45, priceCash: calcCash(9.45), unit: "л", currency: "USD",
    analog: "Євро-Лайтнінг (BASF)", saveFromOriginal: 60,
    cultures: ["sonyashnyk"], stage: ["strakhovyi"], technology: ["clearfield"],
    highlight: true,
    description: "Страховий гербіцид Clearfield. Єдиний надійний інструмент проти нових рас вовчка. Фаза 4-6 листків.",
    descriptionRu: "Страховой гербицид Clearfield. Единственный надёжный инструмент против новых рас заразихи. Фаза 4-6 листьев.",
    image: "/products/torlayting.jpg" },

  { slug: "titon-duo", name: "Тітон Дуо", nameRu: "Титон Дуо", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Мезотріон + Нікосульфурон", activeIngredientRu: "Мезотрион + Никосульфурон",
    concentration: "75 + 30 г/л", packaging: "5 л", rate: "1,25–2,0 л/га",
    priceVat: 9.59, priceCash: calcCash(9.59), unit: "л", currency: "USD",
    analog: "Елюміс (Syngenta)", saveFromOriginal: 69,
    cultures: ["kukurudza"], stage: ["strakhovyi"],
    highlight: true,
    description: "Двокомпонентний страховий гербіцид кукурудзи. Безпечний до 8-го листка.",
    descriptionRu: "Двухкомпонентный страховой гербицид кукурузы. Безопасен до 8-го листа.",
    image: "/products/titon-duo.jpg" },

  // Соняшник — протруйники
  { slug: "bakash-tn", name: "Бакаш ТН", nameRu: "Бакаш ТН", manufacturer: "Нертус", tier: "premium",
    group: "Протруйник", groupSlug: "protruyniky",
    activeIngredient: "Флудиоксоніл + Металаксил + Тіаметоксам", activeIngredientRu: "Флудиоксонил + Металаксил + Тиаметоксам",
    concentration: "комплекс", packaging: "5 л", rate: "1,0–1,5 л/т",
    priceVat: 24.13, priceCash: calcCash(24.13), unit: "л", currency: "USD",
    cultures: ["sonyashnyk"], stage: ["protruyuvannya"], technology: ["klasyka", "clearfield", "express"],
    description: "Триразовий захист насіння: фунгіцид + інсектицид від дротяників.",
    descriptionRu: "Трёхкратная защита семян: фунгицид + инсектицид от проволочников.",
    image: "/products/bakash.jpg" },

  { slug: "trinavata-tn", name: "Тринавата ТН", nameRu: "Тринавата ТН", manufacturer: "Нертус", tier: "premium",
    group: "Протруйник", groupSlug: "protruyniky",
    activeIngredient: "Флудиоксоніл + Металаксил-М", activeIngredientRu: "Флудиоксонил + Металаксил-М",
    concentration: "комплекс", packaging: "5 л", rate: "1,0–1,5 л/т",
    priceVat: 17.09, priceCash: calcCash(17.09), unit: "л", currency: "USD",
    cultures: ["sonyashnyk"], stage: ["protruyuvannya"], technology: ["klasyka", "clearfield", "express"],
    description: "Двокомпонентний фунгіцидний протруйник. Захист від пліснявіння та кореневих гнилей.",
    descriptionRu: "Двухкомпонентный фунгицидный протравитель. Защита от плесневения и корневых гнилей.",
    image: "/products/trinavata.jpg" },

  // Соняшник — ґрунтовий гербіцид
  { slug: "kratos-ke", name: "Кратос КЕ", nameRu: "Кратос КЭ", manufacturer: "Himagro", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Ацетохлор", activeIngredientRu: "Ацетохлор",
    concentration: "900 г/л", packaging: "20 л", rate: "1,5–3,0 л/га",
    priceVat: 4.70, priceCash: calcCash(4.70), unit: "л", currency: "USD",
    analog: "Харнес", saveFromOriginal: 37,
    cultures: ["sonyashnyk", "kukurudza"], stage: ["gruntovyi"], technology: ["klasyka", "clearfield", "express"],
    description: "Ґрунтовий гербіцид для контролю злакових бур'янів. До сходів культури.",
    descriptionRu: "Почвенный гербицид для контроля злаковых сорняков. До всходов культуры.",
    image: "/products/kratos.jpg" },

  { slug: "avatar", name: "Аватар", nameRu: "Аватар", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Ацетохлор", activeIngredientRu: "Ацетохлор",
    concentration: "900 г/л", packaging: "20 л", rate: "1,5–3,0 л/га",
    priceVat: 5.68, priceCash: calcCash(5.68), unit: "л", currency: "USD",
    analog: "Харнес", saveFromOriginal: 37,
    cultures: ["sonyashnyk", "kukurudza"], stage: ["gruntovyi"], technology: ["klasyka", "clearfield", "express"],
    description: "Класичне рішення для довсходових обробок на основі ацетохлору.",
    descriptionRu: "Классическое решение для довсходовых обработок на основе ацетохлора.",
    image: "/products/avatar.jpg" },

  { slug: "zagrey", name: "Загрей", nameRu: "Загрей", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "S-метолахлор + Тербутилазин", activeIngredientRu: "S-метолахлор + Тербутилазин",
    concentration: "312,5 + 187,5 г/л", packaging: "20 л", rate: "3,0–4,5 л/га",
    priceVat: 4.80, priceCash: calcCash(4.80), unit: "л", currency: "USD",
    analog: "Прімекстра TZ Голд",
    cultures: ["sonyashnyk", "kukurudza"], stage: ["gruntovyi"], technology: ["klasyka", "clearfield", "express"],
    description: "Тербутилазин діє за мінімальної вологи — рекомендовано для посушливих умов Півдня.",
    descriptionRu: "Тербутилазин действует при минимальной влаге — рекомендуется для засушливых условий Юга.",
    image: "/products/zagrey.jpg" },

  { slug: "belenus", name: "Беленус", nameRu: "Беленус", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Пропізохлор", activeIngredientRu: "Пропизохлор",
    concentration: "720 г/л", packaging: "20 л", rate: "2,0–3,0 л/га",
    priceVat: 4.76, priceCash: calcCash(4.76), unit: "л", currency: "USD",
    cultures: ["sonyashnyk", "kukurudza"], stage: ["gruntovyi"], technology: ["klasyka", "clearfield", "express"],
    description: "Надійніший за ацетохлор у сухій весні. Не потребує опадів для активації.",
    descriptionRu: "Надёжнее ацетохлора в сухую весну. Не требует осадков для активации.",
    image: "/products/belenus.jpg" },

  // Соняшник — Clearfield
  { slug: "evro-lend-rk", name: "Євро-Ленд РК", nameRu: "Евро-Ленд РК", manufacturer: "Нертус", tier: "premium",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Імазамокс + Імазапір", activeIngredientRu: "Имазамокс + Имазапир",
    concentration: "33 + 15 г/л", packaging: "10 л", rate: "1,0–1,2 л/га",
    priceVat: 13.51, priceCash: calcCash(13.51), unit: "л", currency: "USD",
    analog: "Євро-Лайтнінг (BASF)", saveFromOriginal: 32,
    cultures: ["sonyashnyk"], stage: ["strakhovyi"], technology: ["clearfield"],
    description: "Преміум-дженерик Євро-Лайтнінг. Контроль дводольних, злакових та заразихи.",
    descriptionRu: "Премиум-дженерик Евро-Лайтнинг. Контроль двудольных, злаковых и заразихи.",
    image: "/products/evro-lend.jpg" },

  { slug: "genezys-rk", name: "Генезис РК", nameRu: "Генезис РК", manufacturer: "Укравіт", tier: "premium",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Імазамокс + Імазапір", activeIngredientRu: "Имазамокс + Имазапир",
    concentration: "33 + 15 г/л", packaging: "10 л", rate: "1,0–1,2 л/га",
    priceVat: 9.58, priceCash: calcCash(9.58), unit: "л", currency: "USD",
    analog: "Євро-Лайтнінг (BASF)", saveFromOriginal: 51,
    cultures: ["sonyashnyk"], stage: ["strakhovyi"], technology: ["clearfield"],
    description: "Український аналог Євро-Лайтнінгу. Працює проти заразихи всіх рас. Фаза 4-6 листків.",
    descriptionRu: "Украинский аналог Евро-Лайтнинга. Работает против заразихи всех рас. Фаза 4-6 листьев.",
    image: "/products/genezys.jpg" },

  // Соняшник — Express
  { slug: "hepi-star", name: "Хепі Стар", nameRu: "Хэпи Стар", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Трибенурон-метил", activeIngredientRu: "Трибенурон-метил",
    concentration: "750 г/кг", packaging: "0,5 кг", rate: "0,025–0,050 кг/га",
    priceVat: 26.57, priceCash: calcCash(26.57), unit: "кг", currency: "USD",
    analog: "Гранстар Про", saveFromOriginal: 37,
    cultures: ["sonyashnyk", "ozyma-pshenytsa", "yari-zernovi"], stage: ["strakhovyi", "herbicid-vesna", "herbicid"],
    technology: ["express"],
    description: "Страховий гербіцид Express (СУМО). З ПАР, не вище +25°C.",
    descriptionRu: "Страховой гербицид Express (СУМО). С ПАВ, не выше +25°C.",
    image: "/products/hepi-star.jpg" },

  { slug: "alfa-star-vg", name: "Альфа-Стар ВГ", nameRu: "Альфа-Стар ВГ", manufacturer: "Alfa Smart Agro", tier: "premium",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Трибенурон-метил", activeIngredientRu: "Трибенурон-метил",
    concentration: "750 г/кг", packaging: "0,5 кг", rate: "0,025–0,050 кг/га",
    priceVat: 30.80, priceCash: calcCash(30.80), unit: "кг", currency: "USD",
    analog: "Гранстар Про", saveFromOriginal: 28,
    cultures: ["sonyashnyk", "ozyma-pshenytsa", "yari-zernovi"], stage: ["strakhovyi", "herbicid-vesna", "herbicid"],
    technology: ["express"],
    description: "Преміум-дженерик трибенурон-метилу. Висока якість формуляції.",
    descriptionRu: "Премиум-дженерик трибенурон-метила. Высокое качество формуляции.",
    image: "/products/alfa-star.jpg" },

  // Соняшник — грамініциди
  { slug: "kletekt-mega", name: "Клетект МЕГА", nameRu: "Клетект МЕГА", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Клетодим", activeIngredientRu: "Клетодим",
    concentration: "240 г/л", packaging: "5 л", rate: "0,25–0,6 л/га",
    priceVat: 8.12, priceCash: calcCash(8.12), unit: "л", currency: "USD",
    analog: "Селект",
    cultures: ["sonyashnyk", "soya"], stage: ["graminitsyd"], technology: ["klasyka", "clearfield", "express"],
    description: "Грамініцид проти злакових бур'янів. Не змішувати з протидводольними (5-7 днів).",
    descriptionRu: "Граминицид против злаковых сорняков. Не смешивать с противодвудольными (5-7 дней).",
    image: "/products/kletekt.jpg" },

  { slug: "balor", name: "Балор", nameRu: "Балор", manufacturer: "Нопосон", tier: "econom",
    group: "Гербіцид", groupSlug: "herbitsydy",
    activeIngredient: "Хізалофоп-п-етил", activeIngredientRu: "Хизалофоп-п-этил",
    concentration: "125 г/л", packaging: "5 л", rate: "0,6–1,2 л/га",
    priceVat: 6.77, priceCash: calcCash(6.77), unit: "л", currency: "USD",
    analog: "Фюзілад",
    cultures: ["sonyashnyk", "soya"], stage: ["graminitsyd"], technology: ["klasyka", "clearfield", "express"],
    description: "М'якший до культури, ніж клетодим. Працює навіть в стресових умовах.",
    descriptionRu: "Мягче к культуре, чем клетодим. Работает даже в стрессовых условиях.",
    image: "/products/balor.jpg" },

  // Соняшник — фунгіциди
  { slug: "amikon-ev", name: "Амікон ЕВ", nameRu: "Амикон ЭВ", manufacturer: "Alfa Smart Agro", tier: "premium",
    group: "Фунгіцид", groupSlug: "funhitsydy",
    activeIngredient: "Піраклостробін + Боскалід", activeIngredientRu: "Пираклостробин + Боскалид",
    concentration: "комплекс", packaging: "5 л", rate: "0,5–1,0 л/га",
    priceVat: 17.41, priceCash: calcCash(17.41), unit: "л", currency: "USD",
    analog: "Пiктор (BASF)",
    cultures: ["sonyashnyk"], stage: ["fungicid"], technology: ["klasyka", "clearfield", "express"],
    description: "Преміум-фунгіцид соняшника. Фомоз, альтернаріоз, склеротиніоз. Greening-ефект.",
    descriptionRu: "Премиум-фунгицид подсолнечника. Фомоз, альтернариоз, склеротиниоз. Greening-эффект.",
    image: "/products/amikon.jpg" },

  { slug: "tetris", name: "Тетріс", nameRu: "Тетрис", manufacturer: "PEST.UA", tier: "econom",
    group: "Фунгіцид", groupSlug: "funhitsydy",
    activeIngredient: "Тебуконазол + Дифеноконазол", activeIngredientRu: "Тебуконазол + Дифеноконазол",
    concentration: "комплекс", packaging: "5 л", rate: "0,4–0,6 л/га",
    priceVat: 11.13, priceCash: calcCash(11.13), unit: "л", currency: "USD",
    cultures: ["sonyashnyk", "ozyma-pshenytsa"], stage: ["fungicid", "fungicid-t1"],
    technology: ["klasyka", "clearfield", "express"],
    description: "Двокомпонентний триазол. Найпоширеніші грибкові захворювання соняшника.",
    descriptionRu: "Двухкомпонентный триазол. Распространённые грибковые заболевания подсолнечника.",
    image: "/products/tetris.jpg" },

  { slug: "brander-ks", name: "Брандер КС", nameRu: "Брандер КС", manufacturer: "Нертус", tier: "premium",
    group: "Фунгіцид", groupSlug: "funhitsydy",
    activeIngredient: "Азоксистробін + Ципроконазол", activeIngredientRu: "Азоксистробин + Ципроконазол",
    concentration: "комплекс", packaging: "5 л", rate: "0,8–1,0 л/га",
    priceVat: 18.43, priceCash: calcCash(18.43), unit: "л", currency: "USD",
    analog: "Амістар Екстра (Syngenta)",
    cultures: ["sonyashnyk", "ozyma-pshenytsa"], stage: ["fungicid"], technology: ["klasyka", "clearfield", "express"],
    description: "Стробілуриновий фунгіцид з тривалою дією + greening-ефект.",
    descriptionRu: "Стробилуриновый фунгицид с продолжительным действием + greening-эффект.",
    image: "/products/brander.jpg" },

  // Соняшник — десиканти
  { slug: "batman-rk", name: "Батман РК", nameRu: "Батман РК", manufacturer: "PEST.UA", tier: "econom",
    group: "Десикант", groupSlug: "desykanty",
    activeIngredient: "Дикват", activeIngredientRu: "Дикват",
    concentration: "150 г/л", packaging: "10 л", rate: "2,0–3,0 л/га",
    priceVat: 2.32, priceCash: calcCash(2.32), unit: "л", currency: "USD",
    analog: "Реглон",
    cultures: ["sonyashnyk", "ripak-ozymyi", "ripak-yaryi"], stage: ["desikatsiya"],
    technology: ["klasyka", "clearfield", "express"],
    description: "Десикант для рівномірного дозрівання. При вологості 25-30%. Найдешевший.",
    descriptionRu: "Десикант для равномерного созревания. При влажности 25-30%. Самый дешёвый.",
    image: "/products/batman.jpg" },

  { slug: "skorpion-forte-rk", name: "Скорпіон Форте РК", nameRu: "Скорпион Форте РК", manufacturer: "Нертус", tier: "premium",
    group: "Десикант", groupSlug: "desykanty",
    activeIngredient: "Дикват", activeIngredientRu: "Дикват",
    concentration: "200 г/л", packaging: "10 л", rate: "1,5–2,5 л/га",
    priceVat: 5.50, priceCash: calcCash(5.50), unit: "л", currency: "USD",
    analog: "Реглон Форте",
    cultures: ["sonyashnyk", "ripak-ozymyi", "ripak-yaryi"], stage: ["desikatsiya"],
    technology: ["klasyka", "clearfield", "express"],
    description: "Концентрований десикант з дикватом 200 г/л. Менша норма витрати.",
    descriptionRu: "Концентрированный десикант с дикватом 200 г/л. Меньшая норма расхода.",
    image: "/products/skorpion-forte.jpg" }
];
