// AUTO-GENERATED by scripts/_generate_save_pairs.mjs. DO NOT EDIT MANUALLY.
// Перегенерується автоматично перед `next build` (prebuild hook).
import type { SavePair } from "./types";

export const SAVE_PAIRS: SavePair[] = [
  {
    "ai": "Імідаклоприд, 200 г/л",
    "groupName": "Інсектицид",
    "packaging": "0.5 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Байер",
      "name": "Конфiдор 200SL, РК",
      "priceCash": 46.45,
      "url": "/produkt/konfidor-200sl-rk-baier/3017"
    },
    "our": {
      "brand": "Himagro",
      "name": "ЗЕНІТ, РК",
      "priceCash": 17.92,
      "url": "/produkt/zenit-rk-himagro/3137"
    }
  },
  {
    "ai": "Тіаклоприд, 240 г/л",
    "groupName": "Інсектицид",
    "packaging": "5 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Байер",
      "name": "Бiскайя 240 OD, МД",
      "priceCash": 59.93,
      "url": "/produkt/biskaiya-240-od-baier/3167"
    },
    "our": {
      "brand": "Укравіт",
      "name": "Лювітор, КС",
      "priceCash": 24.25,
      "url": "/produkt/lyuvitor-ks-ukravit/3102"
    }
  },
  {
    "ai": "Прометрин, 500 г/л",
    "groupName": "Гербіцид",
    "packaging": "5 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Сингента",
      "name": "Гезагард 500FW",
      "priceCash": 10.77,
      "url": "/produkt/hezahard-500fw-synhenta/1204"
    },
    "our": {
      "brand": "Alfa Smart Agro",
      "name": "Альфа-Прометрин, КС",
      "priceCash": 4.63,
      "url": "/produkt/alfa-prometryn-ks-alfa-smart-agro/1305"
    }
  },
  {
    "ai": "Пропізохлор, 720 г/л",
    "groupName": "Гербіцид",
    "packaging": "20 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "UPL",
      "name": "Пропоніт",
      "priceCash": 10.12,
      "url": "/produkt/proponit-upl/1353"
    },
    "our": {
      "brand": "PEST.UA",
      "name": "Стівен, КЕ",
      "priceCash": 4.5,
      "url": "/produkt/stiven-ke-pest-ua/1347"
    }
  },
  {
    "ai": "Метрибузин, 600 г/л",
    "groupName": "Гербіцид",
    "packaging": "5 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Байер",
      "name": "Зенкор Лiквiд 600 SC, КС",
      "priceCash": 44.92,
      "url": "/produkt/zenkor-likvid-600-sc-ks-baier/1035"
    },
    "our": {
      "brand": "Нертус",
      "name": "Адвокат, КС",
      "priceCash": 20.27,
      "url": "/produkt/advokat-ks-nertus/1384"
    }
  },
  {
    "ai": "Флуазифоп-П-бутил, 150 г/л",
    "groupName": "Гербіцид",
    "packaging": "20 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Сингента",
      "name": "Фюзiлад Форте150ЕС",
      "priceCash": 23.77,
      "url": "/produkt/fyuzilad-forte150es-synhenta/1225"
    },
    "our": {
      "brand": "Himagro",
      "name": "ЛУАЗИТ, КС",
      "priceCash": 11.59,
      "url": "/produkt/luazyt-ks-himagro/1438"
    }
  },
  {
    "ai": "Імазамокс, 40 г/л",
    "groupName": "Гербіцид",
    "packaging": "5 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Самміт-Агро",
      "name": "Імамекс 40 SL BP",
      "priceCash": 20.44,
      "url": "/produkt/imameks-40-sl-bp-sammit-agro/1173"
    },
    "our": {
      "brand": "Укравіт",
      "name": "Імі-Віт,РК",
      "priceCash": 10.33,
      "url": "/produkt/imi-vit-rk-ukravit/1514"
    }
  },
  {
    "ai": "Ацетохлор, 900 г/л",
    "groupName": "Гербіцид",
    "packaging": "20 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Терра Віта",
      "name": "Пiонер 900 к.е.",
      "priceCash": 8.64,
      "url": "/produkt/pioner-900-k-e-terra-vita/1238"
    },
    "our": {
      "brand": "PEST.UA",
      "name": "Прагмат, КЕ",
      "priceCash": 4.89,
      "url": "/produkt/prahmat-ke-pest-ua/1342"
    }
  },
  {
    "ai": "Тебуконазол, 430 г/л",
    "groupName": "Фунгіцид",
    "packaging": "5 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Самміт-Агро",
      "name": "Ікарус Турбо 430 ЕВ",
      "priceCash": 18.17,
      "url": "/produkt/ikarus-turbo-430-ev-sammit-agro/2130"
    },
    "our": {
      "brand": "АХТ",
      "name": "Полігард Максі",
      "priceCash": 10.44,
      "url": "/produkt/polihard-maksi-akht/2359"
    }
  },
  {
    "ai": "Тіофанат-метил, 500 г/л",
    "groupName": "Фунгіцид",
    "packaging": "5 л",
    "unit": "л",
    "currency": "USD",
    "orig": {
      "brand": "Самміт-Агро",
      "name": "Топсiн-М 500, КС",
      "priceCash": 14.73,
      "url": "/produkt/topsin-m-500-ks-sammit-agro/2141"
    },
    "our": {
      "brand": "Нертус",
      "name": "Тіома, КС",
      "priceCash": 8.77,
      "url": "/produkt/tioma-ks-nertus/2107"
    }
  }
];
