#!/usr/bin/env node
// Сканує public/products/ і формує lib/_image-manifest.ts —
// два Set: коди фасовок та slugs, які реально мають фото на диску.
// ProductImage використовує цей маніфест для синхронного вибору src при SSR,
// без onError-fallback (який раніше ламався при гонці гідратації:
// 404 від <img> прилітав до того, як React встигав прив'язати обробник).
// Запускається автоматично перед `next build` (npm run prebuild).

import { readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const dir = join(root, "public", "products");
const out = join(root, "lib", "_image-manifest.ts");

const codes = [];
const slugs = [];

for (const f of readdirSync(dir)) {
  const m = f.match(/^(.+)\.(jpg|jpeg|png|webp)$/i);
  if (!m) continue;
  const base = m[1];
  if (/^\d{4}$/.test(base)) codes.push(base);
  else slugs.push(base);
}

codes.sort();
slugs.sort();

const content = `// AUTO-GENERATED by scripts/_generate_image_manifest.mjs — do not edit by hand.
// Регенерується автоматично у prebuild перед \`next build\`.
export const productImageCodes = new Set<string>(${JSON.stringify(codes)});
export const productImageSlugs = new Set<string>(${JSON.stringify(slugs)});
`;

writeFileSync(out, content);
console.log(`[image-manifest] ${codes.length} codes + ${slugs.length} slugs → lib/_image-manifest.ts`);
