// Генерує lib/savePairs.generated.ts — топ-10 пар «оригінал ↔ наш аналог» зі спредом 40–65%.
// Запускається prebuild → дані синхронізовані з каталогом при кожному деплої.
// Логіка повторює scripts/_audit_*.mjs пошук: групуємо по нормалізованій діючій речовині,
// беремо найдорожчий original і найдешевший econom/premium з однаковим packaging/unit/currency.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

// ---- 1. Парс products.ts ----
const src = fs.readFileSync(path.join(ROOT, 'lib/products.ts'), 'utf-8');
const startMarker = '_productsData = ';
const startIdx = src.indexOf(startMarker);
const endIdx = src.indexOf('] as const;', startIdx);
if (startIdx === -1 || endIdx === -1) {
  console.error('FAIL: не знайшов _productsData у lib/products.ts');
  process.exit(1);
}
const arrText = src.slice(startIdx + startMarker.length, endIdx + 1); // включаючи ]
const products = new Function(`return ${arrText};`)();
console.log(`[save-pairs] loaded ${products.length} SKU`);

// ---- 2. Пошук пар ----
const norm = (s) => String(s || '').toLowerCase().replace(/\s+/g, ' ').trim();

const groups = new Map();
for (const p of products) {
  if (!p.activeIngredient || !p.priceCash || p.priceOnRequest) continue;
  const k = norm(p.activeIngredient);
  if (!groups.has(k)) groups.set(k, []);
  groups.get(k).push(p);
}

const pairs = [];
for (const [, items] of groups) {
  const originals = items.filter(i => i.tier === 'original');
  const ours = items.filter(i => i.tier === 'econom' || i.tier === 'premium');
  if (!originals.length || !ours.length) continue;

  // По кожному варіанту packaging+unit+currency окремо — щоб порівнювати співмірне.
  const byKey = (i) => `${i.packaging}|${i.unit}|${i.currency}`;
  const oByKey = new Map();
  const usByKey = new Map();
  originals.forEach(o => { if (!oByKey.has(byKey(o)) || oByKey.get(byKey(o)).priceCash < o.priceCash) oByKey.set(byKey(o), o); });
  ours.forEach(u => { if (!usByKey.has(byKey(u)) || usByKey.get(byKey(u)).priceCash > u.priceCash) usByKey.set(byKey(u), u); });

  for (const [key, orig] of oByKey) {
    const our = usByKey.get(key);
    if (!our) continue;
    if (orig.priceCash <= 0 || our.priceCash <= 0) continue;
    const spread = (orig.priceCash - our.priceCash) / orig.priceCash * 100;
    if (spread < 40 || spread > 65) continue;
    pairs.push({
      ai: orig.activeIngredient,
      groupName: orig.group,
      packaging: orig.packaging,
      unit: orig.unit,
      currency: orig.currency,
      orig: {
        brand: orig.manufacturer,
        name: orig.name,
        priceCash: orig.priceCash,
        url: `/produkt/${orig.slug}/${orig.code}`,
      },
      our: {
        brand: our.manufacturer,
        name: our.name,
        priceCash: our.priceCash,
        url: `/produkt/${our.slug}/${our.code}`,
      },
      _spread: spread,
    });
  }
}

pairs.sort((a, b) => b._spread - a._spread);
const top10 = pairs.slice(0, 10).map(({ _spread, ...rest }) => rest);
console.log(`[save-pairs] found ${pairs.length} pairs in 40-65% range, taking top ${top10.length}`);

// ---- 3. Пишемо lib/savePairs.generated.ts ----
const out = `// AUTO-GENERATED by scripts/_generate_save_pairs.mjs. DO NOT EDIT MANUALLY.
// Перегенерується автоматично перед \`next build\` (prebuild hook).
import type { SavePair } from "./types";

export const SAVE_PAIRS: SavePair[] = ${JSON.stringify(top10, null, 2)};
`;

fs.writeFileSync(path.join(ROOT, 'lib/savePairs.generated.ts'), out, 'utf-8');
console.log(`[save-pairs] wrote lib/savePairs.generated.ts (${top10.length} pairs)`);
